### ISSUE TITLE
Notify user at different intervals 

### ISSUE THREAD

**Issue by bsudekum** [mapbox/navigation.js#21]
#### Rules
1. if average speed is greater than 50mph and segment distance is greater than 2 miles, then notify 1 miles out 
   - If this is an interstate to interstate maneuver, do this 2 miles out
2. 150ft out of upcoming maneuver
3. Wait till at least 10 seconds before giving a notification. This to me might be best delegated to the developer.
#### Structure

return an object:

```
alertUser: {
  twoMile: <boolean>,
  oneHundredFiftyFeet: <boolean>
}
```

While `oneHundredFiftyFeet` is true, `twoMile` will also be true. The developer will make sure not spam the user with notifications because since these are boolean, once true it will remain true until the user finishes this segment or is re-routed. 

/cc @1ec5

**Comment by 1ec5** [comment]
> Wait till at least 10 seconds before giving a notification.

I think this heuristic has to be based on instantaneous speed and distance remaining rather than percentage traveled based on expected travel time. Otherwise, the effect is going to vary wildly on unevenly congested roads.

> This to me might be best delegated to the developer.

Absolutely. It’s entirely dependent on how wordy the voice guidance is at that particular moment.

Instead of properties like `twoMile` and `oneHundredFiftyFeet`, how about something that communicates the intention rather than the effect, like `informational` (start thinking about a lane change) and `critical` (turn now).

**Comment by bsudekum** [comment]
> Instead of properties like twoMile and oneHundredFiftyFeet, how about something that communicates the intention rather than the effect, like informational (start thinking about a lane change) and critical (turn now).

Agreed, these could use work. I like `critical`  but I think `informational` is not descriptive enough.
